<?php 




if ( ! defined( 'WPOPTIMIZEBYXTRAFFIC_PLUGIN_VERSION' ) ) {
	define( 'WPOPTIMIZEBYXTRAFFIC_PLUGIN_VERSION', '4.1.11' ); 
}


if ( ! defined( 'WPOPTIMIZEBYXTRAFFIC_PLUGIN_SLUG' ) ) {	//basic 
	define( 'WPOPTIMIZEBYXTRAFFIC_PLUGIN_SLUG', 'wp-optimize-by-xtraffic' );
}

if ( ! defined( 'WPOPTIMIZEBYXTRAFFIC_PLUGIN_OPTIONS_CACHE_KEY' ) ) {
	define( 'WPOPTIMIZEBYXTRAFFIC_PLUGIN_OPTIONS_CACHE_KEY', WPOPTIMIZEBYXTRAFFIC_PLUGIN_SLUG . '-options-cache-key' );
}


if ( ! defined( 'WPOPTIMIZEBYXTRAFFIC_PATH' ) ) { 
	define( 'WPOPTIMIZEBYXTRAFFIC_PATH', WP_CONTENT_DIR . '/plugins/'.WPOPTIMIZEBYXTRAFFIC_PLUGIN_SLUG.'/' );
}


if ( ! defined( 'WPOPTIMIZEBYXTRAFFIC_PLUGIN_NAME' ) ) {
	define( 'WPOPTIMIZEBYXTRAFFIC_PLUGIN_NAME', 'WP Optimize By xTraffic' );
}


if ( ! defined( 'WPOPTIMIZEBYXTRAFFIC_PLUGIN_NS' ) ) {
	define( 'WPOPTIMIZEBYXTRAFFIC_PLUGIN_NS', 'WPOptimizeByxTraffic' );
}



if ( ! defined( 'WPOPTIMIZEBYXTRAFFIC_SITE_CONSTANT_ID' ) ) { 
	
	$wpoptimizebyxtraffic_valueTemp1 = '';
	
	$wpoptimizebyxtraffic_valueTemp1 .= WPOPTIMIZEBYXTRAFFIC_PLUGIN_SLUG;
	$wpoptimizebyxtraffic_valueTemp1 .= __FILE__;
	
	if ( defined( 'AUTH_SALT' ) ) {
		$wpoptimizebyxtraffic_valueTemp1 .= AUTH_SALT;
	}
	
	if ( defined( 'NONCE_SALT' ) ) {
		$wpoptimizebyxtraffic_valueTemp1 .= NONCE_SALT;
	}
	
	if ( defined( 'ABSPATH' ) ) {
		$wpoptimizebyxtraffic_valueTemp1 .= ABSPATH;
	}
	
	define( 'WPOPTIMIZEBYXTRAFFIC_SITE_CONSTANT_ID', md5($wpoptimizebyxtraffic_valueTemp1) ); 
}


if ( ! defined( 'WPOPTIMIZEBYXTRAFFIC_CHMOD' ) ) {
	define( 'WPOPTIMIZEBYXTRAFFIC_CHMOD', 0755 ); 
}



if ( ! defined( 'WPOPTIMIZEBYXTRAFFIC_CACHE_PATH' ) ) {
	define( 'WPOPTIMIZEBYXTRAFFIC_CACHE_PATH', WPOPTIMIZEBYXTRAFFIC_PATH.'inc/cache/' ); 
}


if ( ! defined( 'WPOPTIMIZEBYXTRAFFIC_CACHE_FILES_PATH' ) ) {
	define( 'WPOPTIMIZEBYXTRAFFIC_CACHE_FILES_PATH', WPOPTIMIZEBYXTRAFFIC_CACHE_PATH . 'files/'); 
}

if ( ! defined( 'WPOPTIMIZEBYXTRAFFIC_KEY_DATA_REQUEST' ) ) {
	define( 'WPOPTIMIZEBYXTRAFFIC_KEY_DATA_REQUEST', 'pepvndtecv'); 
}


if ( ! defined( 'WPOPTIMIZEBYXTRAFFIC_UPLOADS_FOLDER_PATH_WP' ) ) {
	define( 'WPOPTIMIZEBYXTRAFFIC_UPLOADS_FOLDER_PATH_WP', WP_CONTENT_DIR . '/uploads/');
}

if ( ! defined( 'WPOPTIMIZEBYXTRAFFIC_UPLOADS_FOLDER_PATH_PEPVN' ) ) {
	define( 'WPOPTIMIZEBYXTRAFFIC_UPLOADS_FOLDER_PATH_PEPVN', WPOPTIMIZEBYXTRAFFIC_UPLOADS_FOLDER_PATH_WP . 'pep-vn' . DIRECTORY_SEPARATOR); 
}

if ( ! defined( 'WPOPTIMIZEBYXTRAFFIC_OPTIMIZE_CACHE_SLUG' ) ) {
	
	define( 'WPOPTIMIZEBYXTRAFFIC_OPTIMIZE_CACHE_SLUG', WPOPTIMIZEBYXTRAFFIC_PLUGIN_SLUG . '-optimize-cache');
}


if ( ! defined( 'WPOPTIMIZEBYXTRAFFIC_WPCONTENT_OPTIMIZE_CACHE_PATH' ) ) {
	define( 'WPOPTIMIZEBYXTRAFFIC_WPCONTENT_OPTIMIZE_CACHE_PATH', WP_CONTENT_DIR . '/cache/' . WPOPTIMIZEBYXTRAFFIC_OPTIMIZE_CACHE_SLUG . '/');
}

